### ISSUE TITLE
Handle persister finalize API error

### ISSUE THREAD

**Issue by aiwilliams** [JupiterOne/sdk#245]
When finalizing a job, if a recoverable error occurs, retry finalization before resorting to aborting the job.

```
err.code | SYNCHRONIZATION_API_RESPONSE_ERROR
-- | --
err.message | Error occurred while finalizing synchronization job. (API response: code=INTERNAL_ERROR, message="Internal server error").
err.name | Error
err.stack | Error: Error occurred while finalizing synchronization job. (API response: code=INTERNAL_ERROR, message="Internal server error").at Object.synchronizationApiError (/opt/lifeomic/app/node_modules/@jupiterone/integration-sdk-runtime/dist/src/synchronization/error.js:11:16)at Object.finalizeSynchronization (/opt/lifeomic/app/node_modules/@jupiterone/integration-sdk-runtime/dist/src/synchronization/index.js:90:23)at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Note that the internal error was a `400` response from ECS task start (ThrottleException), but this is not visible to the SDK, it only sees the `INTERNAL_ERROR` code.

**Comment by aiwilliams** [comment]
Some changes were made in the persister to avoid the ECS task start error (it retries), but we'll still want to improve the resiliency of this system.
